version: '3.7'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kevinliu
      POSTGRES_USER: kevinliu
      POSTGRES_DB: kevinliu
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  server:
    container_name: server
    build: .
    restart: always
    ports:
      - 3000:3000
    links:
      - db
    environment:
      DATABASE_URL: postgres://kevinliu:kevinliu@db:5432/product
